-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Record" DROP CONSTRAINT IF EXISTS "FK_Vin";

ALTER TABLE IF EXISTS public."Vin" DROP CONSTRAINT IF EXISTS "FK_Owner";

ALTER TABLE IF EXISTS public."Vin" DROP CONSTRAINT IF EXISTS "FK_Vehicle";

ALTER TABLE IF EXISTS public."Reminder" DROP CONSTRAINT IF EXISTS "FK_VIN";



DROP TABLE IF EXISTS public."Owner";

CREATE TABLE IF NOT EXISTS public."Owner"
(
    "OwnerId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Owner" PRIMARY KEY ("OwnerId")
);

DROP TABLE IF EXISTS public."Vehicle";

CREATE TABLE IF NOT EXISTS public."Vehicle"
(
    "VehicleId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Year" integer NOT NULL,
    "Make" text NOT NULL,
    "Model" text NOT NULL,
    "Image" text,
    CONSTRAINT "PK_Vehicle" PRIMARY KEY ("VehicleId")
);

DROP TABLE IF EXISTS public."Record";

CREATE TABLE IF NOT EXISTS public."Record"
(
    "RecordId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "VinId" integer NOT NULL,
    "Description" text NOT NULL,
    "Notes" text,
    "DateCompleted" date NOT NULL,
    "DueMileage" integer NOT NULL,
    "CompletedMileage" integer,
    "Cost" integer NOT NULL,
    CONSTRAINT "PK_Record" PRIMARY KEY ("RecordId")
);

DROP TABLE IF EXISTS public."Vin";

CREATE TABLE IF NOT EXISTS public."Vin"
(
    "VinId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Vin" text NOT NULL,
    "Mileage" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "VehicleId" integer NOT NULL,
    CONSTRAINT "PK_Vin" PRIMARY KEY ("VinId")
);

DROP TABLE IF EXISTS public."Reminder";

CREATE TABLE IF NOT EXISTS public."Reminder"
(
    "ReminderId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Description" text NOT NULL,
    "ReminderDate" date,
    "VinId" integer NOT NULL,
    CONSTRAINT "PK_Reminder" PRIMARY KEY ("ReminderId")
);

ALTER TABLE IF EXISTS public."Record"
    ADD CONSTRAINT "FK_Vin" FOREIGN KEY ("VinId")
    REFERENCES public."Vin" ("VinId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Vin"
    ADD CONSTRAINT "FK_Owner" FOREIGN KEY ("OwnerId")
    REFERENCES public."Owner" ("OwnerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."Vin"
    ADD CONSTRAINT "FK_Vehicle" FOREIGN KEY ("VehicleId")
    REFERENCES public."Vehicle" ("VehicleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reminder"
    ADD CONSTRAINT "FK_VIN" FOREIGN KEY ("VinId")
    REFERENCES public."Vin" ("VinId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;