-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.maintenance_record
    DROP CONSTRAINT IF EXISTS "FK_vin";

ALTER TABLE IF EXISTS public.reminder
    DROP CONSTRAINT IF EXISTS "FK_maintenance_record";

ALTER TABLE IF EXISTS public.reminder
    DROP CONSTRAINT IF EXISTS "FK_vin";

ALTER TABLE IF EXISTS public.vin
    DROP CONSTRAINT IF EXISTS "FK_owner";

ALTER TABLE IF EXISTS public.vin
    DROP CONSTRAINT IF EXISTS "FK_vehicle_info";



DROP TABLE IF EXISTS public.maintenance_record;

CREATE TABLE IF NOT EXISTS public.maintenance_record
(
    maintenance_record_id integer                           NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vin_id                integer                           NOT NULL,
    description           text COLLATE pg_catalog."default" NOT NULL,
    notes                 text COLLATE pg_catalog."default",
    date_completed        date,
    mileage_due           integer                           NOT NULL,
    mileage_completed     integer,
    cost                  numeric(2, 0),
    CONSTRAINT "PK_maintenance_record" PRIMARY KEY (maintenance_record_id)
);

DROP TABLE IF EXISTS public.owner;

CREATE TABLE IF NOT EXISTS public.owner
(
    owner_id integer                           NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    email    text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role     text                              NOT NULL,
    CONSTRAINT owner_pkey PRIMARY KEY (owner_id),
    CONSTRAINT "UNIQUE_email" UNIQUE (email)
);

DROP TABLE IF EXISTS public.reminder;

CREATE TABLE IF NOT EXISTS public.reminder
(
    reminder_id   integer                           NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    vin_id        integer                           NOT NULL,
    maintenance_record_id integer,
    description   text COLLATE pg_catalog."default" NOT NULL,
    reminder_date date                              NOT NULL,
    CONSTRAINT "PK_reminder" PRIMARY KEY (reminder_id)
);

DROP TABLE IF EXISTS public.vehicle_info;

CREATE TABLE IF NOT EXISTS public.vehicle_info
(
    vehicle_info_id integer                           NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    year integer NOT NULL,
    make            text COLLATE pg_catalog."default" NOT NULL,
    model           text COLLATE pg_catalog."default" NOT NULL,
    image           text COLLATE pg_catalog."default",
    CONSTRAINT "PK_vehicle_info" PRIMARY KEY (vehicle_info_id)
);

DROP TABLE IF EXISTS public.vin;

CREATE TABLE IF NOT EXISTS public.vin
(
    vin_id          integer                           NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    owner_id        integer                           NOT NULL,
    vehicle_info_id integer                           NOT NULL,
    vin             text COLLATE pg_catalog."default" NOT NULL,
    mileage         integer                           NOT NULL,
    CONSTRAINT "PK_vin" PRIMARY KEY (vin_id)
);

ALTER TABLE IF EXISTS public.maintenance_record
    ADD CONSTRAINT "FK_vin" FOREIGN KEY (vin_id)
        REFERENCES public.vin (vin_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS public.reminder
    ADD CONSTRAINT "FK_maintenance_record" FOREIGN KEY (maintenance_record_id)
        REFERENCES public.maintenance_record (maintenance_record_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.reminder
    ADD CONSTRAINT "FK_vin" FOREIGN KEY (vin_id)
        REFERENCES public.vin (vin_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS public.vin
    ADD CONSTRAINT "FK_owner" FOREIGN KEY (owner_id)
        REFERENCES public.owner (owner_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;


ALTER TABLE IF EXISTS public.vin
    ADD CONSTRAINT "FK_vehicle_info" FOREIGN KEY (vehicle_info_id)
        REFERENCES public.vehicle_info (vehicle_info_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;

END;