-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Owner"
(
    "OwnerId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Owner" PRIMARY KEY ("OwnerId")
);

CREATE TABLE IF NOT EXISTS public."VehicleInfo"
(
    "VehicleInfoId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Year" integer NOT NULL,
    "Make" text NOT NULL,
    "Model" text NOT NULL,
    "Image" text,
    CONSTRAINT "PK_Vehicle" PRIMARY KEY ("VehicleId")
);

CREATE TABLE IF NOT EXISTS public."Record"
(
    "RecordId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "VinId" integer NOT NULL,
    "Description" text NOT NULL,
    "Notes" text,
    "DateCompleted" date NOT NULL,
    "DueMileage" integer NOT NULL,
    "CompletedMileage" integer,
    "Cost" integer NOT NULL,
    CONSTRAINT "PK_Record" PRIMARY KEY ("RecordId")
);

CREATE TABLE IF NOT EXISTS public."Vin"
(
    "VinId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "OwnerId" integer NOT NULL,
    "VehicleInfoId" integer NOT NULL,
    "Vin" text NOT NULL,
    "Mileage" integer NOT NULL,
    CONSTRAINT "PK_Vin" PRIMARY KEY ("VinId")
);

CREATE TABLE IF NOT EXISTS public."Reminder"
(
    "ReminderId" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "VinId" integer NOT NULL,
    "RecordId" integer,
    "Description" text NOT NULL,
    "ReminderDate" date NOT NULL,
    CONSTRAINT "PK_Reminder" PRIMARY KEY ("ReminderId")
);

ALTER TABLE IF EXISTS public."Record"
    ADD CONSTRAINT "FK_Vin" FOREIGN KEY ("VinId")
    REFERENCES public."Vin" ("VinId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vin"
    ADD CONSTRAINT "FK_OWNER" FOREIGN KEY ("OwnerId")
    REFERENCES public."Owner" ("OwnerId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vin"
    ADD CONSTRAINT "FK_VEHICLEINFO" FOREIGN KEY ("VehicleInfoId")
    REFERENCES public."VehicleInfo" ("VehicleInfoId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reminder"
    ADD CONSTRAINT "FK_VIN" FOREIGN KEY ("VinId")
    REFERENCES public."Vin" ("VinId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reminder"
    ADD CONSTRAINT "FK_Record" FOREIGN KEY ("RecordId")
    REFERENCES public."Record" ("RecordId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;