-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.record DROP CONSTRAINT IF EXISTS "FK_vin";

ALTER TABLE IF EXISTS public.vin DROP CONSTRAINT IF EXISTS "FK_owner";

ALTER TABLE IF EXISTS public.vin DROP CONSTRAINT IF EXISTS "FK_vehicle_info";

ALTER TABLE IF EXISTS public.reminder DROP CONSTRAINT IF EXISTS "FK_vin";

ALTER TABLE IF EXISTS public.reminder DROP CONSTRAINT IF EXISTS "FK_record";



DROP TABLE IF EXISTS public.owner;

CREATE TABLE IF NOT EXISTS public.owner
(
    owner_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    user_name text NOT NULL,
    password text NOT NULL,
    PRIMARY KEY (owner_id)
);

DROP TABLE IF EXISTS public.vehicle_info;

CREATE TABLE IF NOT EXISTS public.vehicle_info
(
    vehicle_info_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    year integer NOT NULL,
    make text NOT NULL,
    model text NOT NULL,
    image text,
    CONSTRAINT "PK_vehicle_info" PRIMARY KEY (vehicle_info_id)
);

DROP TABLE IF EXISTS public.record;

CREATE TABLE IF NOT EXISTS public.record
(
    record_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    vin_id integer NOT NULL,
    decription text NOT NULL,
    notes text,
    date_completed date NOT NULL,
    mileage_due integer NOT NULL,
    mileage_completed integer,
    cost numeric(2) NOT NULL,
    CONSTRAINT "PK_record" PRIMARY KEY (record_id)
);

DROP TABLE IF EXISTS public.vin;

CREATE TABLE IF NOT EXISTS public.vin
(
    vin_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    owner_id integer NOT NULL,
    vehicle_info_id integer NOT NULL,
    vin text NOT NULL,
    mileage integer NOT NULL,
    CONSTRAINT "PK_vin" PRIMARY KEY (vin_id)
);

DROP TABLE IF EXISTS public.reminder;

CREATE TABLE IF NOT EXISTS public.reminder
(
    reminder_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    vin_id integer NOT NULL,
    record_id integer,
    description text NOT NULL,
    reminder_date date NOT NULL,
    CONSTRAINT "PK_reminder" PRIMARY KEY (reminder_id)
);

ALTER TABLE IF EXISTS public.record
    ADD CONSTRAINT "FK_vin" FOREIGN KEY (vin_id)
    REFERENCES public.vin (vin_id) MATCH SIMPLE
    ON UPDATE NO ACTION
        ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.vin
    ADD CONSTRAINT "FK_owner" FOREIGN KEY (owner_id)
    REFERENCES public.owner (owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
        ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.vin
    ADD CONSTRAINT "FK_vehicle_info" FOREIGN KEY (vehicle_info_id)
    REFERENCES public.vehicle_info (vehicle_info_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.reminder
    ADD CONSTRAINT "FK_vin" FOREIGN KEY (vin_id)
    REFERENCES public.vin (vin_id) MATCH SIMPLE
    ON UPDATE NO ACTION
        ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.reminder
    ADD CONSTRAINT "FK_record" FOREIGN KEY (record_id)
    REFERENCES public.record (record_id) MATCH SIMPLE
    ON UPDATE NO ACTION
        ON DELETE CASCADE
    NOT VALID;

END;