/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.jdbc)
    api(libs.org.postgresql.postgresql)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(libs.io.jsonwebtoken.jjwt.impl)
    api(libs.io.jsonwebtoken.jjwt.jackson)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.4.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.junit.vintage", "module" to "junit-vintage-engine"))
    }
}

group = "com.capstone"
version = "1.0-SNAPSHOT"
description = "Server"
java.sourceCompatibility = JavaVersion.VERSION_25

// Force Tomcat embed to 10.1.52 to fix 18 CVEs in 10.1.31 (including CRITICAL CVE-2025-24813).
// See: .github/java-upgrade/20260410042749/plan.md
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.apache.tomcat.embed") {
            useVersion("10.1.52")
            because("Fix CVE-2025-24813 (CRITICAL) and 17 other CVEs present in 10.1.31")
        }
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
