GET http://localhost:8080/api/demo/hello

###

GET http://api.carmd.com/v3.0/decode?vin=1GNALDEK9FZ108495
Content-Type: application/json
authorization:
partner-token:


###

GET http://localhost:8080/honestcar/external/test/1GNALDEK9FZ108495
Content-Type: application/json

###

POST http://localhost:8080/test/authenticate
Content-Type: application/json

{
  "email": "test",
  "password": "test"
}

###

POST http://localhost:8080/test/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "email@email.com",
  "password": "password"
}
