@AUTH = {{$processEnv JWT_AUTH_TOKEN}}
@API_AUTH = {{$processEnv API_AUTH}}
@API_TOKEN = {{$processEnv API_TOKEN}}
###

GET http://api.carmd.com/v3.0/decode?vin=1GNALDEK9FZ108495
Content-Type: application/json
authorization: {{API_AUTH}}
partner-token: {{API_TOKEN}}


###


GET http://localhost:8080/api/external/find_vin/1GNALDEK9FZ108495

###

GET http://api.carmd.com/v3.0/maint?vin=1GNALDEK9FZ108495&mileage=51000
authorization: {{API_AUTH}}
partner-token: {{API_TOKEN}}

###

GET http://localhost:8080/api/external/find_maintenance/1GNALDEK9FZ108495/10000

###

POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "email@email.com",
  "password": "password"
}

###

GET http://localhost:8080/api/vin/1
Authorization: Bearer {{AUTH}}

###

GET http://localhost:8080/api/external/find_vin/1GNALDEK9FZ108495
Authorization: Bearer {{AUTH}}

###

POST http://localhost:8080/api/vin
Content-Type: application/json
Authorization: Bearer {{AUTH}}

{
  "ownerId": 1,
  "vin": "test",
  "mileage": 1337,
  "year": 1999,
  "make": "test",
  "model": "test",
  "image": "test"
}

###

POST http://localhost:8080/api/maintenance
Content-Type: application/json
Authorization: Bearer {{AUTH}}

{
  "vinId": 1,
  "description": "test",
  "mileageDue": 1337,
  "cost": 10.00
}

###

PUT http://localhost:8080/api/maintenance
Content-Type: application/json
Authorization: Bearer {{AUTH}}

{
  "maintenanceRecordId": 1,
  "vinId": 1,
  "description": "test",
  "mileageDue": 1337,
  "dateCompleted": "2025-01-01",
  "cost": 10.00
}


###

POST http://localhost:8080/api/maintenance/update_maintenance_records
Content-Type: application/json
Authorization: Bearer {{AUTH}}

[
  {
    "vinId": 1,
    "description": "test",
    "mileageDue": 1337,
    "cost": 10.00
  },
  {
    "vinId": 1,
    "description": "Engine repair",
    "mileageDue": 4500,
    "cost": 200.75
  }
]

###

DELETE http://localhost:8080/api/maintenance/1
Content-Type: application/json
Authorization: Bearer {{AUTH}}

###

GET http://localhost:8080/api/reminder/1
Content-Type: application/json
Authorization: Bearer {{AUTH}}

###

POST http://localhost:8080/api/reminder
Content-Type: application/json
Authorization: Bearer {{AUTH}}

{
  "reminderId": 1,
  "vinId": 1,
  "description": "test",
  "reminderDate": "2025-01-01"
}

###

DELETE http://localhost:8080/api/reminder/delete/1
Content-Type: application/json
Authorization: Bearer {{AUTH}}

###

PUT http://localhost:8080/api/reminder
Content-Type: application/json
Authorization: Bearer {{AUTH}}

{
  "reminderId": 1,
  "vinId": 1,
  "description": "test",
  "reminderDate": "2026-02-02"
}