GET http://localhost:8080/api/demo/hello

###

GET http://api.carmd.com/v3.0/decode?vin=1GNALDEK9FZ108495
Content-Type: application/json
authorization:
partner-token:


###

GET http://localhost:8080/honestcar/external/test/1GNALDEK9FZ108495

###

POST http://localhost:8080/test/authenticate
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password"
}

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "email@email.com",
  "password": "password"
}

###

GET http://localhost:8080/api/vin/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJ0ZXN0IiwibGFzdE5hbWUiOiJ0ZXN0Iiwib3duZXJJZCI6MSwic3ViIjoiZW1haWxAZW1haWwuY29tIiwiaWF0IjoxNzE5MjUzMzI0LCJleHAiOjE3MTkyNTQ3NjR9.ng8V8fAdeXInSVEBsIo0g5nMwQI6Irr-rvqMN5kxLPk
